[workspace]
authors = ["Trim21 <trim21.me@gmail.com>"]
channels = ["conda-forge"]
name = "search"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=2.2.4,<3"
scikit-network = ">=0.33.3,<0.34"
httpx = ">=0.28.1,<0.29"
orjson = ">=3.10.16,<4"
scipy = ">=1.15.2,<2"
tqdm = ">=4.67.1,<5"
